name: terraform-ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: |
            .terraform/providers
            .terraform/plugins
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: '0.45.0'
      - name: Run tflint
        run: |
          tflint --init
          tflint
      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        run: terraform init -backend=false -upgrade -input=false
      - name: Terraform validate
        run: terraform validate -no-color

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'
      - name: Terraform init (no backend)
        run: terraform init -backend=false -upgrade -input=false
      - name: Terraform plan
        run: terraform plan -no-color

  plan_examples:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'
      - name: Init examples
        working-directory: ./examples
        run: terraform init -backend=false -upgrade -input=false
      - name: Plan examples
        working-directory: ./examples
        run: terraform plan -no-color
